import japan from '../content/japan.json';
import seattle from '../content/seattle.json';
import southwest from '../content/southwest.json';
import london from '../content/london.json';
import wedding from '../content/wedding.json';
import honeymoon from '../content/honeymoon.json';

export interface Img { id: string; file: string; w: number; h: number }
export interface Block { type: 'grid' | 'carousel'; images: Img[] }
export interface Section { heading: string; subtitle: string | null; text: string[]; blocks: Block[] }
/** Per-trip look. Every key is optional; anything left out falls back to the site default. See THEMING.md. */
export interface Theme {
  accent?: string;   // eyebrows, active nav, section numbers
  bg?: string;       // page background (light mode)
  bgDark?: string;   // page background (dark mode)
  fg?: string;       // text colour (light mode)
  fgDark?: string;   // text colour (dark mode)
  stage?: string;    // carousel background
  displayFont?: string; // Google Fonts family name for headings, e.g. "Playfair Display"
  bodyFont?: string;    // Google Fonts family name for body text
}
export interface Trip {
  slug: string; title: string; subtitle: string | null; year: number;
  hero: Block[]; sections: Section[]; source: string | null; theme?: Theme;
  date?: string;         // ISO "YYYY-MM-DD" start of trip; drives ordering (falls back to year in title/subtitle)
  placeholder?: boolean; // generated by scripts/placeholders.py, no real photos yet
}

const raw = { southwest, london, japan, seattle, wedding, honeymoon };

// Newest first.
export const trips: Trip[] = Object.entries(raw).map(([slug, t]) => ({
  slug,
  year: Number((t as Trip).date?.slice(0, 4) ?? ((t.title + ' ' + (t.subtitle ?? '')).match(/\d{4}/) ?? [0])[0]),
  ...(t as Omit<Trip, 'slug' | 'year'>),
})).sort((a, b) => (b.date ?? String(b.year)).localeCompare(a.date ?? String(a.year)));

/** Inline CSS custom properties for a trip's theme, applied on <html>. */
export const themeVars = (theme: Theme = {}) => {
  const v: Record<string, string | undefined> = {
    '--accent': theme.accent,
    '--bg-light': theme.bg,
    '--fg-light': theme.fg,
    '--bg-dark': theme.bgDark,
    '--fg-dark': theme.fgDark,
    '--stage': theme.stage,
    '--serif': theme.displayFont && `"${theme.displayFont}", Georgia, serif`,
    '--sans': theme.bodyFont && `"${theme.bodyFont}", -apple-system, system-ui, sans-serif`,
  };
  return Object.entries(v).filter(([, x]) => x).map(([k, x]) => `${k}:${x}`).join(';');
};

/** Google Fonts stylesheet URL covering the site defaults plus any per-trip fonts. */
export const fontsUrl = (theme: Theme = {}) => {
  const fams = ['Fraunces:opsz,wght@9..144,400;9..144,500', 'Inter:wght@400;500;600'];
  for (const f of [theme.displayFont, theme.bodyFont]) if (f) fams.push(`${f.replace(/ /g, '+')}:wght@400;500;600`);
  return `https://fonts.googleapis.com/css2?${fams.map((f) => `family=${f}`).join('&')}&display=swap`;
};

export const bySlug = (slug: string) => trips.find((t) => t.slug === slug)!;

/** URL-safe id for a section heading, used for anchors and the ToC. */
export const sectionId = (heading: string) =>
  heading.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

/** {id, heading} list the TopBar / FloatingToc expect. */
export const sectionsOf = (trip: Trip) =>
  trip.sections.map((s) => ({ id: sectionId(s.heading), heading: s.heading }));

export const allImages = (trip: Trip) =>
  [...trip.hero, ...trip.sections.flatMap((s) => s.blocks)].flatMap((b) => b.images);
